on:
  workflow_call:
  schedule:
    - cron: "0 0 * * *"

jobs:
  auto-update:
    # browniebroke/pre-commit-autoupdate-action
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - run: python -m pip install pre-commit
      - run: pre-commit autoupdate --freeze
      - run: pre-commit run -a
      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: pre-commit-autoupdate
          title: Update pre-commit hooks
          commit-message: "chore: update pre-commit hooks"
          body: Update versions of pre-commit hooks to latest version.
