on:
  push:
  pull_request:

jobs:
  # permissions -> https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idpermissions

  test:
    uses: ./.github/workflows/_test.yml

  pre-commit:
    uses: ./.github/workflows/_pre-commit.yml

  python-semantic-release:
    if: ${{ github.ref == 'refs/heads/master' }}
    uses: ./.github/workflows/_python-semantic-release.yml
    permissions:
      contents: write
    needs:
      - test
      - pre-commit
